services:

  # âœ… Web UI for Docker (Portainer)
  portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      restart: on-failure
      # dns:
      #   - 1.1.1.1
      ports:
        - 9000:9000
        - 9443:9443
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer:/data